sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mustafate/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mustafate/docker-react npm test -- --coverage


